# default settings for datasets per data (rsna_boneage, fae, ...)
defaults:
    rsna_boneage:
        datasets:
            annotations:
                train: /data_fae_uncertainty/rsna_boneage/train_annotations.csv
                val: /data_fae_uncertainty/rsna_boneage/val_annotations.csv
                test: /data_fae_uncertainty/rsna_boneage/test_annotations.csv
            img_base_dirs:
                train: /data_fae_uncertainty/rsna_boneage/train_val
                val: /data_fae_uncertainty/rsna_boneage/train_val
                test: /data_fae_uncertainty/rsna_boneage/test

# model configuration
models:
    rsna_inception_500_gender_mcd:
        data: rsna_boneage
        provider_config:
            base_net: inceptionv3
            uncertainty_method: mc_dropout
            img_input_dimensions: [500, 500]
            variance_net: False
            with_gender_input: True
            rescale_boneage: True
            rebalance_classes: True
        litmodel_config:
            n_samples: 100

    rsna_inception_500_gender_laplace:
        data: rsna_boneage
        provider_config:
            base_net: inceptionv3
            uncertainty_method: laplace_approx
            img_input_dimensions: [500, 500]
            variance_net: False
            with_gender_input: True
            rescale_boneage: True
            rebalance_classes: True
        litmodel_config:
            n_samples: 30

    rsna_inception_500_gender_swag:
        data: rsna_boneage
        provider_config:
            base_net: inceptionv3
            uncertainty_method: swag
            img_input_dimensions: [500, 500]
            variance_net: False
            with_gender_input: True
            rescale_boneage: True
            rebalance_classes: True
        litmodel_config:
            n_samples: 30
            weight_decay: 0.001
            swa_start_epoch: 150
            lr: 0.001
            swa_lrs: 0.0008

    rsna_inception_500_gender_variance_mcd:
        data: rsna_boneage
        provider_config:
            base_net: inceptionv3
            uncertainty_method: mc_dropout
            img_input_dimensions: [500, 500]
            variance_net: True
            with_gender_input: True
            rescale_boneage: True
            rebalance_classes: True
        litmodel_config:
            n_samples: 100
