# default settings for datasets per data (rsna_boneage, fae, ...)
defaults:
    rsna_boneage:
        datasets:
            annotations:
                train: /data_fae_uq/rsna_boneage/train_annotations.csv
                val: /data_fae_uq/rsna_boneage/val_annotations.csv
                test: /data_fae_uq/rsna_boneage/test_annotations.csv
            img_base_dirs:
                train: /data_fae_uq/rsna_boneage/train_val
                val: /data_fae_uq/rsna_boneage/train_val
                test: /data_fae_uq/rsna_boneage/test

# model configuration
models:
    # RSNA Bone Age Model Configurations
    rsna_resnet50_500_gender_mcd:
        data: rsna_boneage
        provider_config:
            base_net: resnet50
            uncertainty_method: mc_dropout
            img_input_dimensions: [500, 500]
            variance_net: False
            with_gender_input: True
            rescale_boneage: True
            rebalance_classes: True
        litmodel_config:
            n_samples: 100

    rsna_resnet50_500_gender_de:
        data: rsna_boneage
        provider_config:
            base_net: resnet50
            uncertainty_method: deep_ensemble
            img_input_dimensions: [500, 500]
            variance_net: False
            with_gender_input: True
            rescale_boneage: True
            rebalance_classes: True

    rsna_resnet50_500_gender_laplace:
        data: rsna_boneage
        provider_config:
            base_net: resnet50
            uncertainty_method: laplace_approx
            img_input_dimensions: [500, 500]
            variance_net: False
            with_gender_input: True
            rescale_boneage: True
            rebalance_classes: True
        litmodel_config:
            n_samples: 30

    rsna_resnet50_500_gender_swag:
        data: rsna_boneage
        provider_config:
            base_net: resnet50
            uncertainty_method: swag
            img_input_dimensions: [500, 500]
            variance_net: False
            with_gender_input: True
            rescale_boneage: True
            rebalance_classes: True
        litmodel_config:
            lr: 0.0003
            weight_decay: 0.00001
            swa_lrs: 0.0003
            swa_start_epoch: 80
            n_samples: 30

    rsna_resnet50_500_gender_swag_high_wd:
        data: rsna_boneage
        provider_config:
            base_net: resnet50
            uncertainty_method: swag
            img_input_dimensions: [500, 500]
            variance_net: False
            with_gender_input: True
            rescale_boneage: True
            rebalance_classes: True
        litmodel_config:
            lr: 0.0003
            weight_decay: 0.01
            swa_lrs: 0.0003
            swa_start_epoch: 80
            n_samples: 30

    rsna_resnet50_500_gender_swag_adam:
        data: rsna_boneage
        provider_config:
            base_net: resnet50
            uncertainty_method: swag
            img_input_dimensions: [500, 500]
            variance_net: False
            with_gender_input: True
            rescale_boneage: True
            rebalance_classes: True
        litmodel_config:
            lr: 0.0003
            optim_type: adam
            weight_decay: 0.001
            swa_lrs: 0.0003
            swa_start_epoch: 80
            n_samples: 30

    rsna_resnet50_500_gender_swag_adam_high_wd:
        data: rsna_boneage
        provider_config:
            base_net: resnet50
            uncertainty_method: swag
            img_input_dimensions: [500, 500]
            variance_net: False
            with_gender_input: True
            rescale_boneage: True
            rebalance_classes: True
        litmodel_config:
            lr: 0.0003
            optim_type: adam
            weight_decay: 0.9
            swa_lrs: 0.0003
            swa_start_epoch: 80
            n_samples: 30

    rsna_resnet50_500_gender_variance_mcd:
        data: rsna_boneage
        provider_config:
            base_net: resnet50
            uncertainty_method: mc_dropout
            img_input_dimensions: [500, 500]
            variance_net: True
            with_gender_input: True
            rescale_boneage: True
            rebalance_classes: True
        litmodel_config:
            n_samples: 100

    rsna_resnet50_500_gender_variance_de:
        data: rsna_boneage
        provider_config:
            base_net: resnet50
            uncertainty_method: deep_ensemble
            img_input_dimensions: [500, 500]
            variance_net: True
            with_gender_input: True
            rescale_boneage: True
            rebalance_classes: True
