# default settings for datasets per data (rsna_boneage, fae, ...)
defaults:
    rsna_boneage:
        datasets:
            annotations:
                train: /data_fae_uq/rsna_boneage/train_annotations.csv
                val: /data_fae_uq/rsna_boneage/val_annotations.csv
                test: /data_fae_uq/rsna_boneage/test_annotations.csv
            img_base_dirs:
                train: /data_fae_uq/rsna_boneage/train_val
                val: /data_fae_uq/rsna_boneage/train_val
                test: /data_fae_uq/rsna_boneage/test
    clavicle_ct:
        datasets:
            annotations:
                train: /data_fae_uq/clavicle_ct/annotations_train.csv
                val: /data_fae_uq/clavicle_ct/annotations_val.csv
                test: /data_fae_uq/clavicle_ct/annotations_test.csv
            img_base_dirs:
                train: /data_fae_uq/clavicle_ct/preprocessed
                val: /data_fae_uq/clavicle_ct/preprocessed
                test: /data_fae_uq/clavicle_ct/preprocessed
        autoencoder:
            ckpt_path: /data_fae_uq/clavicle_ct/agenet18_3d_autoencoder_v1.ckpt

# model configuration
models:
    # RSNA Bone Age Model Configurations
    rsna_resnet50_500_gender_mcd:
        data: rsna_boneage
        provider_config:
            base_net: resnet50
            uncertainty_method: mc_dropout
            img_input_dimensions: [500, 500]
            variance_net: False
            with_gender_input: True
            rescale_boneage: True
            rebalance_classes: True
        litmodel_config:
            n_samples: 100

    rsna_resnet50_500_gender_de:
        data: rsna_boneage
        provider_config:
            base_net: resnet50
            uncertainty_method: deep_ensemble
            img_input_dimensions: [500, 500]
            variance_net: False
            with_gender_input: True
            rescale_boneage: True
            rebalance_classes: True

    rsna_resnet50_500_gender_laplace:
        data: rsna_boneage
        provider_config:
            base_net: resnet50
            uncertainty_method: laplace_approx
            img_input_dimensions: [500, 500]
            variance_net: False
            with_gender_input: True
            rescale_boneage: True
            rebalance_classes: True
        litmodel_config:
            n_samples: 30

    rsna_resnet50_500_gender_swag:
        data: rsna_boneage
        provider_config:
            base_net: resnet50
            uncertainty_method: swag
            img_input_dimensions: [500, 500]
            variance_net: False
            with_gender_input: True
            rescale_boneage: True
            rebalance_classes: True
        litmodel_config:
            lr: 0.0003
            weight_decay: 0.00001
            swa_lrs: 0.0003
            swa_start_epoch: 80
            n_samples: 30

    rsna_resnet50_500_gender_swag_high_wd:
        data: rsna_boneage
        provider_config:
            base_net: resnet50
            uncertainty_method: swag
            img_input_dimensions: [500, 500]
            variance_net: False
            with_gender_input: True
            rescale_boneage: True
            rebalance_classes: True
        litmodel_config:
            lr: 0.0003
            weight_decay: 0.01
            swa_lrs: 0.0003
            swa_start_epoch: 80
            n_samples: 30

    rsna_resnet50_500_gender_swag_adam:
        data: rsna_boneage
        provider_config:
            base_net: resnet50
            uncertainty_method: swag
            img_input_dimensions: [500, 500]
            variance_net: False
            with_gender_input: True
            rescale_boneage: True
            rebalance_classes: True
        litmodel_config:
            lr: 0.0003
            optim_type: adam
            weight_decay: 0.001
            swa_lrs: 0.0003
            swa_start_epoch: 80
            n_samples: 30

    rsna_resnet50_500_gender_swag_adam_low_wd:
        data: rsna_boneage
        provider_config:
            base_net: resnet50
            uncertainty_method: swag
            img_input_dimensions: [500, 500]
            variance_net: False
            with_gender_input: True
            rescale_boneage: True
            rebalance_classes: True
        litmodel_config:
            lr: 0.0003
            optim_type: adam
            weight_decay: 0.0000001
            swa_lrs: 0.0003
            swa_start_epoch: 80
            n_samples: 30

    rsna_resnet50_500_gender_swag_adam_no_wd:
        data: rsna_boneage
        provider_config:
            base_net: resnet50
            uncertainty_method: swag
            img_input_dimensions: [500, 500]
            variance_net: False
            with_gender_input: True
            rescale_boneage: True
            rebalance_classes: True
        litmodel_config:
            lr: 0.0003
            optim_type: adam
            swa_lrs: 0.0003
            swa_start_epoch: 80
            n_samples: 30

    rsna_resnet50_500_gender_variance_mcd:
        data: rsna_boneage
        provider_config:
            base_net: resnet50
            uncertainty_method: mc_dropout
            img_input_dimensions: [500, 500]
            variance_net: True
            with_gender_input: True
            rescale_boneage: True
            rebalance_classes: True
        litmodel_config:
            n_samples: 100

    rsna_resnet50_500_gender_variance_de:
        data: rsna_boneage
        provider_config:
            base_net: resnet50
            uncertainty_method: deep_ensemble
            img_input_dimensions: [500, 500]
            variance_net: True
            with_gender_input: True
            rescale_boneage: True
            rebalance_classes: True

    # Clavicle CT Models
    clavicle_mcd:
        data: clavicle_ct
        provider_config:
            variance_net: False
            uncertainty_method: mc_dropout
            rescale_boneage: True

    clavicle_de:
        data: clavicle_ct
        provider_config:
            variance_net: False
            uncertainty_method: deep_ensemble
            rescale_boneage: True

    clavicle_laplace:
        data: clavicle_ct
        provider_config:
            variance_net: False
            uncertainty_method: laplace_approx
            rescale_boneage: True
        litmodel_config:
            n_samples: 30

    clavicle_swag:
        data: clavicle_ct
        provider_config:
            variance_net: False
            uncertainty_method: swag
            rescale_boneage: True
        litmodel_config:
            lr: 0.0003
            optim_type: adam
            weight_decay: 0.0000001
            swa_lrs: 0.0003
            swa_start_epoch: 80
            n_samples: 30

    clavicle_variance_mcd:
        data: clavicle_ct
        provider_config:
            variance_net: True
            uncertainty_method: mc_dropout
            rescale_boneage: True
        litmodel_config:
            n_samples: 100

    clavicle_variance_de:
        data: clavicle_ct
        provider_config:
            variance_net: True
            uncertainty_method: deep_ensemble
            rescale_boneage: True
